# Generated by Django 2.1.5 on 2019-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
