# Generated by Django 2.1.5 on 2019-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
