# Generated by Django 2.1.5 on 2019-02-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_commu_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commu_Post',
            new_name='CommunicationPost',
        ),
    ]
