# Generated by Django 2.1.5 on 2019-02-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_communicationcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationpost',
            name='photo',
        ),
    ]
