# Generated by Django 2.1.5 on 2019-02-15 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_remove_communicationpost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='explore/post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='communicationcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='explore.CommunicationPost'),
        ),
    ]
