# Generated by Django 2.1.5 on 2019-02-15 05:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_auto_20190215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationpost',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='explore/post/%Y/%m/%d'),
        ),
    ]
