# Generated by Django 2.1.5 on 2019-02-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_auto_20190218_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='communicationpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='communicationcomment',
            old_name='message',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='communicationcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.CommunicationPost'),
        ),
    ]
