# Generated by Django 2.1.5 on 2019-02-21 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_auto_20190220_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
