# Generated by Django 2.1.5 on 2019-02-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_auto_20190221_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationcomment',
            name='content',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='communicationcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.CommunicationPost'),
        ),
    ]
