# Generated by Django 2.1.5 on 2019-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_auto_20190221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationcomment',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
