# Generated by Django 2.1.5 on 2019-02-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_auto_20190221_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.CommunicationPost'),
        ),
        migrations.AlterField(
            model_name='communicationcomment',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='communicationcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='explore.CommunicationPost'),
        ),
    ]
