# Generated by Django 2.1.5 on 2019-02-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0012_auto_20190221_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
