# Generated by Django 2.1.5 on 2019-02-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0013_auto_20190221_1806'),
        ('explore', '0013_auto_20190222_0111'),
    ]

    operations = [
    ]
