# Generated by Django 2.1.5 on 2019-02-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_profile', '0004_auto_20190215_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='accounts.Archive'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
