# Generated by Django 2.1.5 on 2019-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_archive'),
        ('my_profile', '0005_auto_20190219_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='archive',
        ),
        migrations.AddField(
            model_name='post',
            name='archive',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved', to='accounts.Archive'),
        ),
    ]
